#!/usr/bin/env bash

# enable pattern lists like +(...|...)
shopt -s extglob

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Add vendored bin dir to PATH
PATH="${SCRIPT_DIR}/../bin:${PATH}"

# Add included mysql cli to PATH
PATH="${SCRIPT_DIR}/scripts/mysql:${PATH}"
PATH="${HOME}/scripts/mysql:${PATH}"

# Note its nice to be able to run the same script locally as well as in CI,
# so we dont rely on circle env vars being available.

# Note that the .git directory is not included in `cf push`, so the
# GIT_* variables will be empty when run on cf
pushd "${SCRIPT_DIR}" >/dev/null
  IS_GIT=$(git rev-parse --is-inside-work-tree 2>/dev/null)
  if [[ ${IS_GIT} ]]; then
    GIT_BRANCH="$(git symbolic-ref --short -q HEAD)"
  fi
  if [[ -z "$CIRCLECI" ]]; then
    if [[ ${IS_GIT} ]]; then
      GIT_REPO="$(basename `git rev-parse --show-toplevel`)"
    fi
  else
    GIT_REPO="${CIRCLE_PROJECT_REPONAME}"
  fi
popd >/dev/null
